### ISSUE TITLE
Feature Request: Ability to filter download by location

### ISSUE THREAD

**Issue by see24** [ABbiodiversity/wildRtrax#15]
As a user who is no affiliated with any of the projects or organizations directly, the project names and organizations are not very meaningful. What I want is all the data available for a given location. So far the only way I have found to figure out which projects that includes is to use the Data Discover webpage to search all organizations and projects for the sensor type I want and zoom in on the area and write down the organizations with data in that area. And then download the data for those organizations.

Ideally there would be a way to filter the Data Discover webpage by location or more importantly to provide an extent or polygon to a download function that would find all the data in WildTrax for that area. For example the [bcdata](https://github.com/bcgov/bcdata) package can do this and it is really useful!

I imagine that would involve fairly deep changes to the way the data is stored on WildTrax so another interim solution would be to add some location information to the project metadata returned by `wt_get_download_summary` such as a list of jurisdictions, BCRs or ecozones where the project has data, or even just a min and max latitude and longitude for each project. This would be very helpful to avoid having to download more data before filtering. 

Thanks for the package!

**Comment by agmacpha** [comment]
@see24 We see value in providing extent options to `wt_get_download_summary()` and will consider this for development. Thank you for the suggestion!

**Comment by agmacpha** [comment]
Functionality for location filtering added in 1.3 in `wt_dd_summary()`
