### ISSUE TITLE
Add to Docs: sensor_id can be "PC"

### ISSUE THREAD

**Issue by see24** [ABbiodiversity/wildRtrax#16]
I am able to run `wt_get_download_summary(sensor_id = "PC")` and get results but according to the docs only "ARU" and "CAM" are options. It would also be nice if there was a check that `sensor_id` is one of the possible options. If you try "PNTCNT" for example you just get a dplyr error that is not very informative.
 
https://github.com/ABbiodiversity/wildRtrax/blob/78f277f9b9eb082128db75c498019dcbd06050cb/R/api.R#L33

**Comment by see24** [comment]
Actually just noticed that the table returned by `wt_get_download_summary(sensor_id = "PC")` also contains all the ARU projects

**Comment by agmacpha** [comment]
@see24 WildTrax has implemented functionality that converts ARU data into PC format so you can use `wt_get_donwload_summary(sensor_id = "PC")` and it will return ARU projects you can combine into your PC work flow. We will provide some better documentation and error reporting on this front! Thank you!

**Comment by agmacpha** [comment]
Enhancement made to documentation here: https://abbiodiversity.github.io/wildRtrax/articles/apis.html

**Comment by see24** [comment]
@agmacpha This is an improvement but it is still not clear to me what is done when I have sensor_id = "PC". Is there a more specific link that could be added to the APIs vignette so that people can know what that means? The BAM website and GitHub organization might contain the information to explain that but I don't know where or what it would even be called. 

In the Acoustic data wrangling vignette they use sensor_id = "ARU" when is this preferable? Maybe this could be where more details are given for what is being done if is doesn't fit well in the APIs vignette. 

It would also help if there was some more info describing what the sensor_id argument does in the function documentation. My assumption based on the function docs and argument name was that this would filter the data in the requested project to just the requested sensor type but it also does this whole conversion process from ARU to PC which I wouldn't have guessed from the function docs and may not be desirable for all users.

**Comment by agmacpha** [comment]
Hi Sarah

Thank you for your questions

Selecting sensor_id = 'PC' for an ARU project will convert the ARU
formatted-data into the point count sensor format. These conversion scripts
were facilitated by a partnership between BAM and WildTrax as the point
count sensor was specifically designed to house all BAM managed data.

sensor_id simply corresponds to which sensor you're wishing to download
data from, the current options include ARU, CAM or PC.

We can certainly provide additional information to this effect to
clarify the functionality

Thank you for your continued supportive communication around wildRtrax!

**Comment by see24** [comment]
Hi Alex, 

Coming back to this I still find the current set up misleading and think it sweeps a significant step under the rug in a way that makes it harder to understand the data. Since you said you could provide more information it would be great if you could re-open the issue until that is available. Thanks!

_Selecting sensor_id = 'PC' for an ARU project will convert the ARU formatted-data into the point count sensor format. These conversion scripts were facilitated by a partnership between BAM and WildTrax as the point count sensor was specifically designed to house all BAM managed data._ 

Ok does this mean that all the counts that come from ARUs are stored in two separate tables in your database? So if I use the argument sensor_id = 'ARU' I am downloading the data as transcribed in the ARU tasks but if I have sensor_id = 'PC' for the same project I will get a version of that data where some post-processing has been done to make the ARU data look like and  theoretically be equivalent to data that would have been collected by a human point count at that location?

My concern is that a naïve user might think that because they selected sensor_id = 'PC' they would only get data where the sensor used to collect the data was a human point count without knowing in advance what type of field sensor was used for the project. This makes in seem like data collected by point count and data collected by ARU then converted to a point count can be treated the same which might be the goal of that conversion but which I would want to keep in mind as a user. 

_sensor_id simply corresponds to which sensor you're wishing to download data from, the current options include ARU, CAM or PC._ 

As a user I expect sensor_id to reflect the sensor the data was collected **with** not the table it is stored on in your database. I think this would be much more transparent if there was a separate argument for saying whether I want the raw version of the ARU data or the post-processed to be like point count data version. That way if supply sensor_id = 'PC' for a project where the field sensor used was an ARU I would get the same message I get if I had supplied 'CAM' because that is not the sensor that was used to collect data in this project. If I want data modified to be like a point count I should have to acknowledge that this is happening by setting sensor_id = 'ARU' and convert_to_PC = TRUE (or whatever you want to call it). 

_We can certainly provide additional information to this effect to clarify the functionality_
More information would be really great because I am interested in the methods that BAM used but have not been able to find them.
