### ISSUE TITLE
Feature Request: Path to store downloaded files

### ISSUE THREAD

**Issue by see24** [ABbiodiversity/wildRtrax#19]
It would be nice if there was an argument in `wt_download_report` for a file path to store the downloaded files. This would prevent having to re-download the files every time a script is re-run which would help to encourage a reproducible workflow. 

An example of a similar function is in [bbsAssistant](https://github.com/trashbirdecology/bbsAssistant/blob/main/R/grab_bbs_data.R) the `grap_bbs_data` function has a directory argument and an overwrite arugment to force a fresh download.

**Comment by agmacpha** [comment]
@see24 If you're interested in the csvs, I would recommend going to WildTrax and using Data Downloads. The purpose of `wt_download_report()` is to allow users to directly store their WildTrax as R objects, skipping the need to deal with csvs. If you're downloading a large data set, we recommend for example saving it to an `.RData` file.

**Comment by see24** [comment]
I am not interested in the csvs themselves just in avoiding the need to re-download them every time I want to re-run my script from scratch which I try to do often to ensure everything still works. The download took between 20 and 45 mins so it is a lot of time that I could save by just keeping the file instead of deleting them. I can implement this myself by saving the whole thing to a file and checking if it exists but I still think it would be a nice feature to have the option in the function.
