### ISSUE TITLE
Error returning Riff headers

### ISSUE THREAD

**Issue by cbedge** [ABbiodiversity/wildRtrax#2]
Unexpected Error occurs when running some, but not all recordings with the wt_audio_scanner() function on a batch of files. Error has been isolated to recordings from specific Songmeter SM2+ units
i `data = furrr::future_map(...)`.
x This seems not to be a valid RIFF file of type WAVE.
Run `rlang::last_error()` to see where the error occurred.
In addition: There were 14 warnings (use warnings() to see them)

**Comment by agmacpha** [comment]
Hi @cbedge. We've made an improvement in the development branch of `wt_audio_scanner` that will by default avoid scanning files that are header-less or missing the RIFF header. We will release this in the near future along will other improvements. Thanks for reporting this issue!
