### ISSUE TITLE
Feature Request: Faster method for downloading multiple reports

### ISSUE THREAD

**Issue by see24** [ABbiodiversity/wildRtrax#20]
Sorry for all the requests! Just getting into this package so I have a few ideas, hopefully they are helpful!

Based on the [APIs vignette](https://abbiodiversity.github.io/wildRtrax/articles/apis.html) I have been using `purrr::map` to run `wt_download_report` to download each report one at a time and add the data to a tibble. 

```r
# Download all of the published ARU data from CWS-ONT
aru_projects <- wt_get_download_summary(sensor_id = "ARU") %>%
  as_tibble()

system.time(
  cwsON_arus <- aru_projects %>%
                        filter(status == "Published - Public",
                               grepl('^CWS-Ontario', project)) %>%
                        dplyr::mutate(data = purrr::map(
                          .x = project_id,
                          .f = ~wt_download_report(project_id = .x, sensor_id = "ARU",
                                                   weather_cols = T, reports = "main"))) %>%
                        select(-project_id, -organization) %>%
                        unnest(data)
)
 ## user  system elapsed 
 ## 111.97   25.72 2676.70 
```

However, this takes a long time (~45 mins) and seems inefficient since `wt_download_report` has to download and unzip each file one by one. On the other hand it seems like when you select multiple projects and download them by hand on the WildTrax website the datasets are combined into one zip file. I assume that would be faster than downloading and unzipping each one individually. In addition, is there a reason to download all the report csv files when only the main report is requested? If it was possible to only download the requested report that might help. 

Also I noticed in the source code for  `wt_download_report` that all the reports are read with `read.csv` into a list and then they are filtered down to just the requested reports. If you filtered the filenames first so you only read in the requested csv that would speed things up. You might also want to consider using readr::read_csv or data.table::fread since they can be much faster.

**Comment by mabecker89** [comment]
Hi @see24 — I just tried downloading the same set of reports as you and it took me ~20 min (1221 seconds). Have you updated the package to the most recent version? The latest change does exactly what you suggest, where only the reports specifically requested (e.g., "main" here) are returned. Other reports should not be downloaded by the API in this latest version (i.e., in the query_list object, they will be set to FALSE).  

I'll look into read_csv and fread and see if there are performance improvements! Thanks!

**Comment by see24** [comment]
I can see the change you made for the adding PC to the sensor_id options. Is that recent enough or do you mean the development branch?

**Comment by agmacpha** [comment]
Replace read.csv with read_csv. Feel free to re-open if you're still seeing performance issues @see24
