### ISSUE TITLE
'year' error when loading data

### ISSUE THREAD

**Issue by ctlamb** [ABbiodiversity/wildRtrax#3]
When I call either wt_get_download_summary() or wt_download_report() I get the following "Column `year` doesn't exist." error. Seems odd, seeing as the same script worked earlier this month. But I tried restarting R, and reloading WildRTrax (but I had the lastest version). Can anyone confirm if they get this error, or is it some odd package conflict on my end of something.

```
> wildRtrax::wt_get_download_summary(sensor_id = 'CAM')
Error in `stop_subscript()`:
! Can't subset columns that don't exist.
x Column `year` doesn't exist.
Backtrace:
  1. wildRtrax::wt_get_download_summary(sensor_id = "CAM")
  4. dplyr:::select.data.frame(...)
  5. tidyselect::eval_select(expr(c(...)), .data)
  6. tidyselect:::eval_select_impl(...)
 14. tidyselect:::vars_select_eval(...)
     ...
 21. tidyselect:::chr_as_locations(x, vars)
 22. vctrs::vec_as_location(x, n = length(vars), names = vars)
 23. vctrs `<fn>`()
 24. vctrs:::stop_subscript_oob(...)
 25. vctrs:::stop_subscript(...)
```

**Comment by ecknight** [comment]
I'm getting a similar one: 

> my_projects <- wt_get_download_summary(sensor_id = 'ARU')
Error in `dplyr::select()`:
! Can't subset columns past the end.
x Column `year` doesn't exist.

Perhaps something to do with the updated output release. I'll chat with Marcus

**Comment by mabecker89** [comment]
Sorry both, just seeing this. Will work on an update to handle the new data download formats and let you know when it's done.

**Comment by dhope** [comment]
I had the same issue and tracked it down to the updated summary not including year in the download: https://github.com/ABbiodiversity/wildRtrax/blob/91c404ff158de2e5d96ae8b38396d239d3e499ca/R/api.R#L56. 

I've been using this to get around it until the package handles the updated API. 
https://gist.github.com/dhope/d38fff2937ff3ef203051b1f88138c7f

**Comment by mabecker89** [comment]
Hi everyone. Issue has been fixed now if you want to redownload the package. Thanks for you patience. I'll close the issue at the end of this week if no one reports any other related issues.
