### ISSUE TITLE
wt_get_download_summary() do not return organization

### ISSUE THREAD

**Issue by MelinaHoule** [ABbiodiversity/wildRtrax#4]
Information about the type of sensor is found in the summary table (wt_get_download_summary()). A user that wants to recover sensor type for a specific project needs to merge the project report with its respective summary. However, the only column those two tables has in common is  **project**. Organization is missing from wt_get_download_summary(). Unfortunately, the field **project** isn't unique in the summary table, which prevent the merge to operate properly. Summary table should return organization and project in order successfully assign sensor type to the right project report. 

```r
my_projects <- wt_get_download_summary(sensor_id = 'PC')
my_projects[duplicated(my_projects$project),]
output:
      project project_id sensorId tasks             status
139 Big Grids         31      ARU  7609 Published - Public

my_projects[my_projects$project == "Big Grids",]
output:
      project project_id sensorId tasks             status
138 Big Grids        381      ARU  2236             Active
139 Big Grids         31      ARU  7609 Published - Public
```

**Comment by mabecker89** [comment]
Sorry for the late replay @MelinaHoule. This is great suggestion, will add organization to the function in the upcoming release (early January).

**Comment by agmacpha** [comment]
@MelinaHoule recent release should have resolved this issue. `wt_get_download_summary` now includes project_id and `wt_download_report` reports include project_id and organization acronyms

**Comment by see24** [comment]
It would still be very helpful if the organization acronym was in the `wt_get_download_summary` table. For example I wanted all data from CWS-ONT and luckily for me all their projects have CWS-Ontario at the start of the name but that is not true for all organizations.

**Comment by mabecker89** [comment]
Hi Sarah, I just pushed a fix for this issue here https://github.com/ABbiodiversity/wildRtrax/commit/8d67df8f571b0537cf9ae8f1291c7db4f22e40e3

If you re-download the package, you'll be able to use `wt_get_download_summary()` and obtain organization in the table.
