### ISSUE TITLE
Project report dowload as list

### ISSUE THREAD

**Issue by angelXmonster** [ABbiodiversity/wildRtrax#49]
Brief description of the problem

I was downloading the data of protect "Eastmain 1A Powerhouse and Rupert Diversion Project EIA 2002" (project_id=837) and it downloaded a list with 4 elements.

```r
wt_download_report(project_id = 837, 
                                       sensor = "PC", 
                                       weather_cols = F, 
                                       report = "main"))
```

**Comment by agmacpha** [comment]
@angelXmonster thank you for submitting this issue. We are working to ensure that the PC sensor data is sending only one report at a time as requested.

**Comment by agmacpha** [comment]
@angelXmonster We've resolved this issue with an impending push we intend to release soon; since the string 'main' was also in the project name, it was pulling all reports, thus creating the list.
