### ISSUE TITLE
Add DOI and citation.cff?

### ISSUE THREAD

**Issue by NickleDave** [ABbiodiversity/wildRtrax#6]
Hi, I'd like to potentially cite this software in an article discussing annotations for audio. I understand from @ecknight that you may add functions soon for downloading annotations from WildTrax.

This is not quite a feature request or bug, then. But just thought I'd suggest you add a DOI, e.g. with [GitHub's zenodo integration](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content), and a [citation.cff](https://citation-file-format.github.io/) file, to make the software more easily citable. AFAICT `wildRtrax` does not have either now, although I'm happy to learn I'm wrong.

**Comment by mabecker89** [comment]
Hi @NickleDave - Thanks for the suggestion! We'll make sure to do in conjunction with the upcoming release in January.

**Comment by NickleDave** [comment]
Perfect, thank you @mabecker89, will watch for the release

**Comment by agmacpha** [comment]
@NickleDave CITATION.cff added. please let us know if you need anything else

**Comment by NickleDave** [comment]
Nice! Thank you
