### ISSUE TITLE
Feature request: cameras days with issues removed from effort

### ISSUE THREAD

**Issue by ctlamb** [ABbiodiversity/wildrtrax#62]
Include functionality to remove portions of effort period in `wt_summarise_cam()` where camera is not operating properly (i.e., covered by snow, or fov changed). Generally, this would include removing periods where image_fov=="Out of Range".

The proposal would be to have an effort variable based on timed images, where effort equals the number of days over the period of interest with a timed image where image_fov!="Out of Range"

**Comment by alexmacphail** [comment]
Completed with commit [eecccb0](https://github.com/ABbiodiversity/wildrtrax/commit/eecccb02ec4b724cc71d35cb12b84cfe259105b6)
