### ISSUE TITLE
wt_download_report not working for sensor_id='CAM'

### ISSUE THREAD

**Issue by RyanFisherSK** [ABbiodiversity/wildRtrax#8]
When I use wt_download_report for any camera data I always receive a failure when receiving data. I've tried adjusting/increasing the timeout period, but that doesn't seem to work either. wt_download_report for ARU downloads works fine and no issues. Other download functions also seem to work fine (e.g., wt_get_download_summary downloads and returns data).

```r
library(wildRtrax)

#Sets login info for WildTrax
Sys.setenv(WT_USERNAME = 'xxxxx', WT_PASSWORD = 'xxxx')
wt_auth()
#> Authentication into WildTrax successful.

#Download report of urban widllife cameras
taginfo <- wt_download_report(project_id = 1105, sensor_id = 'CAM', report="tag")

Downloading: 18 MB
#> Error in curl::curl_fetch_disk(url, x$path, handle = handle): Failure when receiving data from the peer
```

<sup>Created on 2023-08-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

```

**Comment by mabecker89** [comment]
Hey Ryan, sorry for the delay!

We've updated the `wt_download_report` function a bit - can you re-download the package and try again with your project id?

Did you find this with just the 'tag' report, or were other reports (e.g., 'main') not working either? 

Another thing to try may be to reinstall the `curl` package to make sure it's up to date.

**Comment by RyanFisherSK** [comment]
Hi Marcus, After updating the package and updating curl, everything seems to be working again.
Thank you!

**Comment by mabecker89** [comment]
Glad to hear it!
